volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/margarida/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/margarida/data/wordpress
      o: bind
      type: none

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    networks:
      - inception
  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    restart: unless-stopped
    expose:
      - "9000"
    networks:
      - inception
    depends_on:
      - mariadb


networks:
  inception:
    driver: bridge