volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/margarida/data/mariadb
      o: bind
      type: none

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    networks:
      - inception

networks:
  inception:
    driver: bridge